# fly.toml app configuration file generated for weather-data on 2023-07-14T23:43:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weather-data"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  JWT_SECRET = "thisisasamplesecret"
  JWT_ACCESS_EXPIRATION_MINUTES = "43200"
  JWT_REFRESH_EXPIRATION_DAYS = "43200"
  JWT_RESET_PASSWORD_EXPIRATION_MINUTES = "10"
  JWT_VERIFY_EMAIL_EXPIRATION_MINUTES = "10"
  SMTP_HOST = "email-server"
  SMTP_PORT = "1025"
  SMTP_USERNAME = "cxbcjhxbcxc"
  SMTP_PASSWORD = "mnxkcjxcjk"
  EMAIL_FROM = "dkfdk@dfnfdkj.com"
  COOKIE_SECRET = "dfkhdkjfdf"
  CLIENT_URL = "http://localhost:5000"

[build]
  build-target = "production"

[experimental]
cmd = ["yarn", "start"]

